### ISSUE TITLE
implementation

### ISSUE THREAD

**Issue by caffeinum** [h4sh3d/xmr-btc-atomic-swap#3]
Did you plan to implement it in JavaScript or Go?

**Comment by h4sh3d** [comment]
I have no direct plan to implement this now, but if I do I’ll probably use TypeScript and/or Rust.

**Comment by caffeinum** [comment]
I am working on an open-source atomic swap protocol, we mainly use JS, and we already have BTC, ETH, ERC20, EOS, LTC, BCH, USDT swaps. It would be nice to add a Monero swaps, do you wish to collaborate?

**Comment by h4sh3d** [comment]
Thank's for proposing but I don't have time to contribute now
